services:
  db:
    image: postgres:latest
    restart: unless-stopped 
    container_name: postgres_db
    hostname: postgres_db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: demo_service_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d
    env_file:
      - .env
volumes:
  pgdata: