services:
  db:
    image: postgres:latest
    restart: unless-stopped 
    container_name: ${CONTAINER_NAME}
    hostname: ${HOSTNAME}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data 
      - ./docker/postgres:/docker-entrypoint-initdb.d
    env_file:
      - .env