services:
  db:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
  kafka:
    image: bitnami/kafka:3.7
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093

      - KAFKA_CFG_LISTENERS=OUTER://:9092,CONTROLLER://:9093,INNER://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=INNER://kafka:9094,OUTER://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=OUTER:PLAINTEXT,CONTROLLER:PLAINTEXT,INNER:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INNER
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server localhost:9094 --list >/dev/null 2>&1"]
      interval: 10s    
      timeout: 5s            
      retries: 5       
      start_period: 30s 
  app:
    build: .
    container_name: app
    environment:      
      APP_DB_PORT: 5432
      APP_DB_HOST: postgres

      KAFKA_PORT: 9094
      KAFKA_HOST: kafka
      
      APP_HOST: 0.0.0.0   
      APP_PORT: 8080

      KAFKA_TOPIC: order
      KAFKA_GROUP_ID: order-processor-v1
    ports:
      - "8081:8080"
    env_file:
      - .env
    depends_on:
      db: 
        condition: service_healthy
      kafka:
        condition: service_healthy
      

volumes:
  pgdata:
  kafkaData:


